version: '3.1'

services:
  postgres:
    image: postgres:11
    restart: always
    ports:
      - '5432'
    environment:
      POSTGRES_DB: '${POSTGRES_DB_DATABASE}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  mysql:
    image: mysql:8
    restart: always
    ports:
      - '3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DB_DATABASE}'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  busybox:
    image: busybox
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
