name: Database Library Tests

on: workflow_dispatch

env:
  DB_DATABASE: my_db_test
  DB_USER: root
  DB_PASSWORD: root
  DB_HOST: 127.0.0.1
  DB_PORT: 3306

jobs:
  dbsetup:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        py-db-module: ["pymysql", "pyodbc", "pymssql"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up MySQL
        # mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ matrix.py-db-module }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -e "SHOW DATABASES;" -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          netstat -ano
      - name: Download the Sakila Database
        run: |
          wget -P /tmp/ https://downloads.mysql.com/docs/sakila-db.zip
          unzip /tmp/sakila-db.zip -d /tmp
      - name: Setup Database
        #  mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D${{ env.DB_DATABASE }} < /tmp/sakila-db/sakila-schema.sql
        #  mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D${{ env.DB_DATABASE }} < /tmp/sakila-db/sakila-data.sql
        run: |
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D${{ matrix.py-db-module }} < /tmp/sakila-db/sakila-schema.sql
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D${{ matrix.py-db-module }} < /tmp/sakila-db/sakila-data.sql
      - name: Setup MySQL ODBC Drivers
        #  sudo apt-get install libmyodbc      
        if: matrix.py-db-module == 'pyodbc'
        run: |
          wget -qO - https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo sh -c 'echo "deb https://packages.microsoft.com/ubuntu/18.04/prod bionic main" > /etc/apt/sources.list.d/mssql-release.list'
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
          rpm -qa | grep -i odbc
      - name: Setup MySQL ODBC Drivers
        if: matrix.py-db-module == 'pymssql'
        run: |
          sudo apt-get install tdsodbc
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.7'
      - name: Setup Python Packaging and Pip
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Setup Robot Framework
        run: |
          pip install robotframework
      - name: Install Development/Checked out version of DatabaseLibrary
        run: |
          pip install ${{ github.workspace }}/.
      - name: Setup Python DB module
        run: |
          pip install ${{ matrix.py-db-module }}
      - name: Run Robot Framework tests using PyMySQL
        if: matrix.py-db-module == 'pymysql'
        working-directory: ./test
        run: |
          robot -d pymysql/ -v DBName:${{ matrix.py-db-module }} -v DBUser:${{ env.DB_USER }} -v DBPass:${{ env.DB_PASSWORD }} -v DBHost:${{ env.DB_HOST }} -v DBPort:${{ env.DB_PORT }} ${{ github.workspace }}/test/MySQL_DB_Tests.robot
      - name: Run Robot Framework tests using PyODBC
        if: matrix.py-db-module == 'pyodbc'
        working-directory: ./test
        run: |
          python3 -c "import pyodbc; print(pyodbc.drivers())"
          robot --loglevel TRACE -d pyodbc/ -v DBName:${{ matrix.py-db-module }} -v DBUser:${{ env.DB_USER }} -v DBPass:${{ env.DB_PASSWORD }} -v DBHost:localhost -v DBPort:${{ env.DB_PORT }} -v dbDriver:"ODBC Driver 17 for SQL Server" ${{ github.workspace }}/test/PyODBC_DB_Tests.robot
      - name: Run Robot Framework tests using PyMSSQL
        if: matrix.py-db-module == 'pymssql'
        working-directory: ./test
        run: |
          robot -d pymssql/ -v DBName:${{ matrix.py-db-module }} -v DBUser:${{ env.DB_USER }} -v DBPass:${{ env.DB_PASSWORD }} -v DBHost:${{ env.DB_HOST }} -v DBPort:${{ env.DB_PORT }} ${{ github.workspace }}/test/MSSQL_DB_Tests.robot
      - name: Run Robot Framework tests using ${{ matrix.py-db-module }}
        if: matrix.py-db-module == 'ignore-all-modules'
        working-directory: ./test
        run: |
          robot -v DBName:${{ matrix.py-db-module }} -v DBUser:${{ env.DB_USER }} -v DBPass:${{ env.DB_PASSWORD }} -v DBHost:${{ env.DB_HOST }} -v DBPort:${{ env.DB_PORT }} ${{ github.workspace }}/test/PyODBC_DB_Tests.robot
      - name: Upload Robot Logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: log-files
          path: ./test/