name: Database Library Tests

on: workflow_dispatch

env:
  DB_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: root

jobs:
  dbsetup:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "SHOW DATABASES;" -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Download the Sakila Database
        run: |
          wget -P /tmp/sakila-db/ https://downloads.mysql.com/docs/sakila-db.zip
          unzip /tmp/sakila-db.zip
      - name: Setup Database
        run: |
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D{{ env.DB_DATABASE }} < /tmp/sakila-db/sakila-schema.sql
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D{{ env.DB_DATABASE }} < /tmp/sakila-db/sakila-data.sql