name: Database Library Tests

on: workflow_dispatch

env:
  DB_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: root

jobs:
  dbsetup:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        py-db-module: ["pymysql", "pyodbc"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -e "SHOW DATABASES;" -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Download the Sakila Database
        run: |
          wget -P /tmp/ https://downloads.mysql.com/docs/sakila-db.zip
          unzip /tmp/sakila-db.zip -d /tmp
      - name: Setup Database
        run: |
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D${{ env.DB_DATABASE }} < /tmp/sakila-db/sakila-schema.sql
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -D${{ env.DB_DATABASE }} < /tmp/sakila-db/sakila-data.sql
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Python Packaging and Pip
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Setup Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-dblibrary
      - name: Setup Python DB module
        run: |
          pip install ${{ matrix.py-db-module }}
      - name: Run Robot Framework tests using PyMySQL
        if: matrix.py-db-module == 'pymysql'
        run: |
          robot -v DBUser:${{ env.DB_USER }} -v DBPass:${{ env.DB_PASSWORD }} ${{ github.workspace }}/tests/MySQL_DB_Tests.robot
          